import type { LoginSettings } from './types/loginSettings'

// Debe coincidir con los DEFAULT de database/migrations/005_create_login_settings.sql —
// se usa como valor inicial mientras carga /settings/login y como fallback si falla.
export const DEFAULT_LOGIN_SETTINGS: LoginSettings = {
  systemName: 'LeagueCore',
  title: 'LeagueCore',
  subtitle: 'Sistema de gestión de ligas y competiciones',
  welcomeMessage: 'Accedé para continuar',
  showLogo: true,
  showSubtitle: true,
  showWelcomeMessage: true,
  logoMainUrl: null,
  logoLoginUrl: null,
  backgroundType: 'color',
  backgroundImageUrl: null,
  backgroundVideoUrl: null,
  backgroundVideoMuted: true,
  backgroundVideoStartSeconds: null,
  backgroundVideoEndSeconds: null,
  backgroundColor: '#0f172a',
  backgroundPosition: 'center',
  backgroundSize: 'cover',
  backgroundRepeat: 'no-repeat',
  overlayColor: '#000000',
  overlayOpacity: 0,
  colorPrimary: '#2563eb',
  colorSecondary: '#1e293b',
  colorText: '#0f172a',
  colorTextSecondary: '#64748b',
  colorFormBg: '#ffffff',
  colorFormBgOpacity: 1,
  colorButton: '#2563eb',
  colorButtonHover: '#1d4ed8',
  colorError: '#dc2626',
  colorBorder: '#cbd5e1',
  colorInputBg: '#ffffff',
  buttonText: 'Iniciar sesión',
  placeholderUsername: 'Ingresá tu usuario',
  placeholderPassword: 'Ingresá tu contraseña',
}
